model:
  node_dim: 64
  edge_dim: 5
  global_dim: 19
  hidden_dim: 256
  global_node_dim: 256

train:
  epochs: 30
  lr: 1e-4
  loss: mse

dataset:
  graph_dir: gs://k8s-idp-storage/data/graphs
  label_dir: gs://k8s-idp-storage/data/labels

device:
  device: cuda
