model:
  node_dim: 30
  edge_dim: 5
  global_dim: 18
  hidden_dim: 256
  global_node_dim: 256

train:
  epochs: 2
  lr: 0.0001
  loss: mse

dataset:
  graph_dir: data/graphs
  label_dir: data/labels

device:
  device: cpu
