model:
  node_dim: 30
  edge_dim: 5
  global_dim: 18
  hidden_dim: 256
  global_node_dim: 256

train:
  epochs: 10
  lr: 0.000001  # Reduced from 1e-5 to 1e-6 for stability
  loss: mse
  batch_size: 16

dataset:
  graph_dir: data/graphs
  label_dir: data/labels
  max_samples: 10000

device:
  device: cpu
