model:
  node_dim: 30
  edge_dim: 5
  global_dim: 18
  hidden_dim: 256
  global_node_dim: 256

train:
  epochs: 5
  lr: 0.00001  # 10배 감소
  loss: mse
  batch_size: 16  # 더 큰 배치

dataset:
  graph_dir: data/graphs
  label_dir: data/labels
  max_samples: 10000 # 10000개만 테스트

device:
  device: cpu
