model:
  node_dim: 30
  edge_dim: 5
  global_dim: 18
  hidden_dim: 256
  global_node_dim: 256

train:
  epochs: 1
  lr: 0.0001
  loss: mse
  batch_size: 1

dataset:
  graph_dir: data/graphs
  label_dir: data/labels
  max_samples: 10  # 처음 10개만 테스트

device:
  device: cpu
